# Generated by Django 3.2.9 on 2021-11-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP Address from which the user last logged in', null=True, verbose_name='IP Address'),
        ),
    ]
