# Generated by Django 3.2.9 on 2021-11-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20211123_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='administration.usermodel', to_field='username', verbose_name='User')),
                ('authorization_token', models.CharField(help_text='Authorization Token of the user to interact with the API, auto-generated', max_length=255, serialize=False, unique=True, verbose_name='Authorization Token')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP Address from which the user last logged in', null=True, verbose_name='IP Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='authorization_token',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='ip_address',
        ),
    ]
