# Generated by Django 3.2.9 on 2021-11-25 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20211125_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationmodel',
            name='user',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='User'),
        ),
    ]
