# Generated by Django 4.0.1 on 2022-01-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name of the User', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Last Name of the User', max_length=255, null=True, verbose_name='Last Name')),
                ('email_id', models.EmailField(help_text='Email ID of the User', max_length=1023, verbose_name='Email ID')),
                ('message', models.TextField(help_text='Message by the User', verbose_name='Message')),
            ],
        ),
    ]
