# Generated by Django 3.2.9 on 2021-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name of the User', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last Name of the User', max_length=50, verbose_name='Last Name')),
                ('email_id', models.EmailField(help_text='Email ID of the User', max_length=255, verbose_name='Email ID')),
                ('message', models.TextField(help_text='Message by the User', verbose_name='Message')),
            ],
        ),
    ]
