# Generated by Django 4.0.1 on 2022-02-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_set', to='root.teacher'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assignment_set', to='api.Class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.fileassets'),
        ),
    ]
