# Generated by Django 3.2.9 on 2021-12-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date for which the timetable is valid. Represented by `datetime.date` instance.', verbose_name='Date')),
                ('grade', models.CharField(help_text='The grade for which the timetable is valid. Should be a string', max_length=5, unique_for_date='date', verbose_name='Grade')),
                ('periods', models.JSONField(default=[], help_text='A list of dictionaries having field keys as `time` and `subject` and field values as the time in string valid for the period and the subject of which the period is respectively.', verbose_name='Periods')),
            ],
        ),
    ]
