# Generated by Django 4.0.1 on 2022-02-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_subject_unique_together_alter_student_grade_and_more'),
        ('api', '0002_subject_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assigned_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Assigned at')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission Date')),
                ('message', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Message')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_set', to='root.teacher')),
                ('assigned_to', models.ManyToManyField(related_name='assignment_set', to='api.Class')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.fileassets')),
            ],
        ),
    ]
