# Generated by Django 4.0.1 on 2022-02-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_set', to='root.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_set', to='root.parent'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_set', to='root.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'code')},
        ),
    ]
